### ISSUE TITLE
Work with animation

### ISSUE THREAD

**Issue by AlexeyKorkoza** [pub-t/destination#10]
1. Animate.css 
   Link: https://github.com/daneden/animate.css .
   Docs: in Readme.md
   My opinion: there are many different effects in this library. It is very easy to use. In Readme.md full information about to use the Animate.css
2. Angular-animate.js
   Link: https://github.com/angular/bower-angular-animate
   Docs: https://docs.angularjs.org/api/ngAnimate
   My opinion: good library with a well described documentations. Many examples are in the documents.

**Comment by irnc** [comment]
I guess that `ngAnimate` is for Angular.js 1.x only.

Quick search suggested https://www.youtube.com/watch?v=izp5N2eeogg for animation in Angular 2.
