### ISSUE TITLE
Change the sequence of actions in the client-side

### ISSUE THREAD

**Issue by KrivichaninDenis** [pub-t/destination#18]
**1.** Изначально пользователь видит поле ввода "Куда" и кнопку "Найти маршрут". Далее при вводе конечного пункта и нажатии кнопки у пользователя спрашивается разрешение на определение его местоположения.
    1.1  Если пользователь дал доступ, сформировать запрос `{ from: { lat, long }, to: String }`.
    1.2 Если пользователь не дал доступ, то появляется второе поле "Откуда" и при заполнении обоих полей и нажатии на кнопку "Найти маршрут" формируется запрос `{ from: String, to: String }`.
**2.**  После отправки запроса у пользователя отображается подсказка с текстовой инструкцией(формат инструкции пока прорабатывается) и кнопка "Найти маршрут" будет отображаться только после изменения полей "Откуда" и "Куда".
**3.** Для более детального отображения маршрута пользователю будет доступ перех на карту на которой будет отображен маршрут его движения до конечной точки

**Comment by irnc** [comment]
It is unclear what should be changed and why. Please add explanatory description.
