### ISSUE TITLE
Написать простой сервер для обработки пользовательского ввода

### ISSUE THREAD

**Issue by KrivichaninDenis** [pub-t/destination#8]
Клиентская часть делает запрос к данному серверу(string), данный сервер обрабатывает запрос.
Возвращает инструкцию куда идти и через сколько ближайший транспорт(Если пользователь хочет  наглядно посмотреть куда идти можно будет посмотреть на карте куда двигаться)

**Comment by irnc** [comment]
Думаю для этих целей мы создали https://github.com/pub-t/name-to-point, задачи по его реализации нужно размещать там.

**Comment by KrivichaninDenis** [comment]
Да,конечно.Так только что и продумали
